SHARED_PARAMS = [
    {"env": "QA_PHONE_NUMBER",       "label": "QA Phone Number",        "type": "text",     "required": True,  "placeholder": "5122227114"},
    {"env": "QA_IP_ADDRESS",         "label": "IP Address",             "type": "text",     "required": False, "placeholder": "79.116.129.221"},
    {"env": "QA_EMAIL",              "label": "QA Email",               "type": "text",     "required": False, "placeholder": "iccantimbuhan@gmail.com"},
    {"env": "QA_JORNAYA_LEADID",     "label": "Jornaya Lead ID",        "type": "text",     "required": False, "placeholder": "93C30C8C-FA4F-D125-0622-2D176826CBED"},
    {"env": "SLACK_WEBHOOK_URL",     "label": "Slack Webhook (QA)",     "type": "password", "required": False, "placeholder": "https://hooks.slack.com/services/..."},
    {"env": "SMS_SLACK_WEBHOOK_URL", "label": "Slack Webhook (SMS)",    "type": "password", "required": False, "placeholder": "https://hooks.slack.com/services/..."},
]

PROVIDER_SCHEMAS = [
    {
        "key":    "heavy_khomp",
        "name":   "Heavy Khomp",
        "module": "providers.heavy_khomp",
        "params": [
            {"env": "HEAVY_KHOMP_API_KEY",     "label": "API Key",     "type": "password", "required": True,  "default": ""},
            {"env": "HEAVY_KHOMP_FIRST_NAME",  "label": "First Name",  "type": "text",     "required": False, "default": "Justin Bieber"},
            {"env": "HEAVY_KHOMP_STATE",       "label": "State",       "type": "text",     "required": False, "default": "FL"},
            {"env": "HEAVY_KHOMP_POSTAL_CODE", "label": "Postal Code", "type": "text",     "required": False, "default": "32004"},
        ],
    },
    {
        "key":    "heavy_khomp_dynamic",
        "name":   "Heavy Khomp (Dynamic)",
        "module": "providers.heavy_khomp_dynamic",
        "params": [
            {"env": "HEAVY_KHOMP_DYNAMIC_API_KEY",     "label": "API Key",     "type": "password", "required": True,  "default": ""},
            {"env": "HEAVY_KHOMP_DYNAMIC_FIRST_NAME",  "label": "First Name",  "type": "text",     "required": False, "default": "Prince"},
            {"env": "HEAVY_KHOMP_DYNAMIC_LAST_NAME",   "label": "Last Name",   "type": "text",     "required": False, "default": "Canlas"},
            {"env": "HEAVY_KHOMP_DYNAMIC_CITY",        "label": "City",        "type": "text",     "required": False, "default": "Manhattan"},
            {"env": "HEAVY_KHOMP_DYNAMIC_STATE",       "label": "State",       "type": "text",     "required": False, "default": "New York"},
            {"env": "HEAVY_KHOMP_DYNAMIC_POSTAL_CODE", "label": "Postal Code", "type": "text",     "required": False, "default": "10001"},
            {"env": "HEAVY_KHOMP_DYNAMIC_SUBID_1",    "label": "Sub ID 1",    "type": "text",     "required": False, "default": "Heavy Khomp One"},
            {"env": "HEAVY_KHOMP_DYNAMIC_SUBID_2",    "label": "Sub ID 2",    "type": "text",     "required": False, "default": "Heavy Khomp Two"},
            {"env": "HEAVY_KHOMP_DYNAMIC_SUBID_3",    "label": "Sub ID 3",    "type": "text",     "required": False, "default": "Heavy Khomp Three"},
            {"env": "HEAVY_KHOMP_DYNAMIC_SUBID_4",    "label": "Sub ID 4",    "type": "text",     "required": False, "default": "Heavy Khomp Four"},
            {"env": "HEAVY_KHOMP_DYNAMIC_SUBID_5",    "label": "Sub ID 5",    "type": "text",     "required": False, "default": "Heavy Khomp Five"},
            {"env": "HEAVY_KHOMP_DYNAMIC_SUBID_6",    "label": "Sub ID 6",    "type": "text",     "required": False, "default": "Heavy Khomp Six"},
            {"env": "HEAVY_KHOMP_DYNAMIC_SUBID_7",    "label": "Sub ID 7",    "type": "text",     "required": False, "default": "Heavy Khomp Seven"},
            {"env": "HEAVY_KHOMP_DYNAMIC_SUBID_8",    "label": "Sub ID 8",    "type": "text",     "required": False, "default": "Heavy Khomp Eight"},
            {"env": "HEAVY_KHOMP_DYNAMIC_SUBID_9",    "label": "Sub ID 9",    "type": "text",     "required": False, "default": "Heavy Khomp Nine"},
            {"env": "HEAVY_KHOMP_DYNAMIC_SUBID_10",   "label": "Sub ID 10",   "type": "text",     "required": False, "default": "Heavy Khomp Ten"},
        ],
    },
    {
        "key":    "lite_khomp",
        "name":   "Lite Khomp",
        "module": "providers.lite_khomp",
        "params": [
            {"env": "LITE_KHOMP_API_KEY",     "label": "API Key",     "type": "password", "required": True,  "default": ""},
            {"env": "LITE_KHOMP_FIRST_NAME",  "label": "First Name",  "type": "text",     "required": False, "default": "John Lite"},
            {"env": "LITE_KHOMP_LAST_NAME",   "label": "Last Name",   "type": "text",     "required": False, "default": "Khomp"},
            {"env": "LITE_KHOMP_CITY",        "label": "City",        "type": "text",     "required": False, "default": "Manhattan"},
            {"env": "LITE_KHOMP_STATE",       "label": "State",       "type": "text",     "required": False, "default": "New York"},
            {"env": "LITE_KHOMP_POSTAL_CODE", "label": "Postal Code", "type": "text",     "required": False, "default": "10001"},
        ],
    },
    {
        "key":    "tbi_khomp",
        "name":   "TBI Khomp",
        "module": "providers.tbi_khomp",
        "params": [
            {"env": "TBI_KHOMP_API_KEY",     "label": "API Key",     "type": "password", "required": True,  "default": ""},
            {"env": "TBI_KHOMP_FIRST_NAME",  "label": "First Name",  "type": "text",     "required": False, "default": "John TBI"},
            {"env": "TBI_KHOMP_LAST_NAME",   "label": "Last Name",   "type": "text",     "required": False, "default": "Khomp"},
            {"env": "TBI_KHOMP_STATE",       "label": "State",       "type": "text",     "required": False, "default": "FL"},
            {"env": "TBI_KHOMP_POSTAL_CODE", "label": "Postal Code", "type": "text",     "required": False, "default": "32004"},
        ],
    },
    {
        "key":    "tbi_fs",
        "name":   "TBI Freeswitch",
        "module": "providers.tbi_fs",
        "params": [
            {"env": "TBI_FS_API_KEY",     "label": "API Key",     "type": "password", "required": True,  "default": ""},
            {"env": "TBI_FS_FIRST_NAME",  "label": "First Name",  "type": "text",     "required": False, "default": "John TBI"},
            {"env": "TBI_FS_LAST_NAME",   "label": "Last Name",   "type": "text",     "required": False, "default": "Freeswitch"},
            {"env": "TBI_FS_STATE",       "label": "State",       "type": "text",     "required": False, "default": "FL"},
            {"env": "TBI_FS_POSTAL_CODE", "label": "Postal Code", "type": "text",     "required": False, "default": "32004"},
        ],
    },
    {
        "key":    "signalmash_khomp",
        "name":   "Signalmash Khomp",
        "module": "providers.signalmash_khomp",
        "params": [
            {"env": "SIGNALMASH_KHOMP_API_KEY",     "label": "API Key",     "type": "password", "required": True,  "default": ""},
            {"env": "SIGNALMASH_KHOMP_FIRST_NAME",  "label": "First Name",  "type": "text",     "required": False, "default": "John Signalmash"},
            {"env": "SIGNALMASH_KHOMP_LAST_NAME",   "label": "Last Name",   "type": "text",     "required": False, "default": "Khomp"},
            {"env": "SIGNALMASH_KHOMP_STATE",       "label": "State",       "type": "text",     "required": False, "default": "FL"},
            {"env": "SIGNALMASH_KHOMP_POSTAL_CODE", "label": "Postal Code", "type": "text",     "required": False, "default": "32004"},
        ],
    },
    {
        "key":    "signalmash_fs",
        "name":   "Signalmash Freeswitch",
        "module": "providers.signalmash_fs",
        "params": [
            {"env": "SIGNALMASH_FS_API_KEY",     "label": "API Key",     "type": "password", "required": True,  "default": ""},
            {"env": "SIGNALMASH_FS_FIRST_NAME",  "label": "First Name",  "type": "text",     "required": False, "default": "John Signalmash"},
            {"env": "SIGNALMASH_FS_LAST_NAME",   "label": "Last Name",   "type": "text",     "required": False, "default": "Freeswitch"},
            {"env": "SIGNALMASH_FS_STATE",       "label": "State",       "type": "text",     "required": False, "default": "FL"},
            {"env": "SIGNALMASH_FS_POSTAL_CODE", "label": "Postal Code", "type": "text",     "required": False, "default": "32004"},
        ],
    },
    {
        "key":    "accident_office",
        "name":   "Accident Office (RetellAI)",
        "module": "providers.accident_office",
        "params": [
            {"env": "ACCIDENT_OFFICE_API_KEY",     "label": "API Key",     "type": "password", "required": True,  "default": ""},
            {"env": "ACCIDENT_OFFICE_FIRST_NAME",  "label": "First Name",  "type": "text",     "required": False, "default": "Rene"},
            {"env": "ACCIDENT_OFFICE_STATE",       "label": "State",       "type": "text",     "required": False, "default": "FL"},
            {"env": "ACCIDENT_OFFICE_POSTAL_CODE", "label": "Postal Code", "type": "text",     "required": False, "default": "32004"},
            {"env": "ACCIDENT_OFFICE_SUBID_1",     "label": "Sub ID 1",    "type": "text",     "required": False, "default": "test"},
            {"env": "ACCIDENT_OFFICE_SUBID_2",     "label": "Sub ID 2",    "type": "text",     "required": False, "default": "test"},
        ],
    },
    {
        "key":    "sms_signalmash",
        "name":   "SMS Only — Signalmash",
        "module": "providers.sms_signalmash",
        "params": [
            {"env": "SMS_SIGNALMASH_API_KEY",     "label": "API Key",     "type": "password", "required": True,  "default": ""},
            {"env": "SMS_SIGNALMASH_FIRST_NAME",  "label": "First Name",  "type": "text",     "required": False, "default": "Taehyung"},
            {"env": "SMS_SIGNALMASH_POSTAL_CODE", "label": "Postal Code", "type": "text",     "required": False, "default": "32004"},
        ],
    },
    {
        "key":    "sms_ai_signalmash",
        "name":   "SMS with AI — Signalmash",
        "module": "providers.sms_ai_signalmash",
        "params": [
            {"env": "SMS_AI_SIGNALMASH_API_KEY",     "label": "API Key",     "type": "password", "required": True,  "default": ""},
            {"env": "SMS_AI_SIGNALMASH_FIRST_NAME",  "label": "First Name",  "type": "text",     "required": False, "default": "Jungkook"},
            {"env": "SMS_AI_SIGNALMASH_POSTAL_CODE", "label": "Postal Code", "type": "text",     "required": False, "default": "32004"},
        ],
    },
]
